### ISSUE TITLE
Make Import functions more modular

### ISSUE THREAD

**Issue by jan-petr** [ExploreASL/ExploreASL#394]
- Remove the duplicity between ExploreASL_Import and ExploreASL_ImportBIDS
- Put all possible parts of code to separate subfunctions for these two functions
- Improve the modularity and readability of the code.
- Make it modular enough so that Beatriz can run the json parsing only for fixing OASIS.

#### Things we could start with
1. Create a subfolder `SubModule_Import` within the `Modules` folder 👍 
2. Move `ExploreASL_ImportBIDS` to the `Modules folder` 👍 
3. Add the `SubModule_Import` folder to the function `addExploreASLDirectory(MyPath)` in `ExploreASL_Initialize 👍 
4. Move the subfunctions of `ExploreASL_ImportBIDS` as separate scripts to the `SubModule_Import` folder 👍 

#### Compare `ExploreASL_ImportBIDS` and `ExploreASL_Import` versions for...
- `CatchErrors`
- `AppendNiftiParameters`
- `AppendParmsParameters`

#### Use `ExploreASL_ImportBIDS_DCM2NII` within `ExploreASL_Import`

- `ExploreASL_Import` uses `_imp_` subfunctions now 👍 
- **TODO**

#### Fix remaining bugs during flavor processing

- **TODO**

#### Create new subfunctions for...
- create summary file 👍 
- xASL_imp_DCM2NII_Initialize 👍 
- xASL_imp_DCM2NII_Subject 👍 
- xASL_imp_NII2BIDS_Subject 👍 

#### Write cases from `ExploreASL_ImportConfig` to `JSONs`

- Check out `BIDS_createTemplatesImportConfig` 👍 

#### Remove `ExploreASL_ImportConfig` step by step

- Check out the `ConfigFiles` folder within the `CustomScripts` repository 👍 
- Check out the simplified `ExploreASL_ImportConfig` script 👍 

#### OASIS related JSON metadata fix?

- **TODO**

**Comment by jan-petr** [comment]
### Comment by Henk
1) anonimize using dcm2nn
2) zeroing images (Marco does this)
3) manually verify that no retraceable data is left

-> we also need to make sure that the UIDs pointing to a center/site are gone too.
-> also need to make sure there are no privacy-sensitive data stored 
encrypted by the vendor in some private fields, or in the XML/Phoenix attachments

But for now, for internal testing, we can skip the above, and simply state in the paper what kind of "flavors" were tested.
We only put the 3 datasets in the "ImportBIDS*" folder online. Then it would be good to also have a multi-TI example online.

### Answer Jan
1) For flavors, I have anonymized using the tool by Paul Groot.
For BIDS, no anonymization was necessary since NII only are added and DCMs are from Patricia and Joseph and Sjoerd.
2) Zeroing was done for BIDS only, but not for Flavors - because we need the data.
3) it should be 99% good, but not 100% - needs to be verified and cannot be released yet.
4) UIDs are probably taken care of by the anonymized of DCMs.
5) We need to check again Phoenixes.

**Comment by MichaelStritt** [comment]
### Test Flavor: GE_PCASL_2DEPI_volunteer (Windows)

### - [logContent.xlsx](https://github.com/ExploreASL/ExploreASL/files/6316892/logContent.xlsx)

**Comment by MichaelStritt** [comment]
### Test Flavors: All GE datasets (Windows)

### - [logContent.xlsx](https://github.com/ExploreASL/ExploreASL/files/6317742/logContent.xlsx)
### - [logFullPipelineTest.txt](https://github.com/ExploreASL/ExploreASL/files/6317744/logFullPipelineTest.txt)

**Comment by MichaelStritt** [comment]
@jan-petr: Do you want to have a quick look at what I've worked on so far?

**Comment by MichaelStritt** [comment]
@jan-petr: I think you're right, probably something goes wrong in `xASL_imp_DCM2NII_Subject`:

### GE_PCASL_3Dspiral_Product_volunteer (windows)
```console
...
--------------------------------------------------------------------------------
Chris Rorden's dcm2niiX version v1.0.20190902  (JP2:OpenJPEG) (JP-LS:CharLS) MSC1900 (64-bit Windows)
Found 72 DICOM file(s)
Warning: Empty protocol name(s) (0018,1030)
Warning: Unable to append protocol name (0018,1030) to filename (it is empty).
Warning: This diffusion series does not have a B0 (reference) volume
Warning: Some images had bval>0 but bvec=0 (either Trace or b=0, see issue 245)
Convert 36 DICOM as 
    .\FlavorTests\TmpConversion\GE_PCASL_3Dspiral_Product_volunteer
    \analysis\Sub1\ASL_1\dcm2nii_temp_ASL4D\ASL__20130408103133_8 (128x128x36x1)
Warning: Unable to append protocol name (0018,1030) to filename (it is empty).
Warning: This diffusion series does not have a B0 (reference) volume
Warning: Some images had bval>0 but bvec=0 (either Trace or b=0, see issue 245)
Convert 36 DICOM as 
    .\FlavorTests\TmpConversion\GE_PCASL_3Dspiral_Product_volunteer
    \analysis\Sub1\ASL_1\dcm2nii_temp_ASL4D\ASL__20130408103133_8a (128x128x36x1)
Conversion required 0.283000 seconds.
--------------------------------------------------------------------------------
status: 0
Shuffle the dynamics...
.\FlavorTests\TmpConversion\GE_PCASL_3Dspiral_Product_volunteer\analysis\Sub1\ASL_1\ASL4D_1.nii
.\FlavorTests\TmpConversion\GE_PCASL_3Dspiral_Product_volunteer\analysis\Sub1\ASL_1\ASL4D_a_2.nii
Warning: concatenating multiple NIfTIs & jsons as output from dcm2niiX
Corrected dcm2niiX output for GE files and found the correct scan order:
.\FlavorTests\TmpConversion\GE_PCASL_3Dspiral_Product_volunteer\analysis\Sub1\ASL_1\ASL4D.nii
deltam,m0scan
...
```

... I checked the individual scans within [MicroDicom](https://www.microdicom.com/). But there it seems as if `deltam,m0scan` is correct, since they start with DWIs and end with an M0 scan.

**Comment by MichaelStritt** [comment]
`ASL4D_a_2` definitely looks like an m0 scan to me and `ASL4D_1` should be a PWI.

**Comment by MichaelStritt** [comment]
Other minor question: is there an option to select the atlases for the population module within `studyPar.json` already? Or where would we do this?

**Comment by jan-petr** [comment]
> `ASL4D_a_2` definitely looks like an m0 scan to me and `ASL4D_1` should be a PWI.

Yes - so the question is how is this sorted in Linux and under Windows - which one flips the order and how to solve. From your comments, I am not able to guess what goes wrong - shall we have a short meeting about this?

**Comment by jan-petr** [comment]
> Other minor question: is there an option to select the atlases for the population module within `studyPar.json` already? Or where would we do this?

What exactly you mean? in normal StudyPar there is the x.S.Atlases option for this - wasn't it you adding it there? Or you mean to add it to DataPar.json in import so that it is saved to StudyPar in derivatives?

**Comment by MichaelStritt** [comment]
> What exactly you mean? in normal StudyPar there is the x.S.Atlases option for this - wasn't it you adding it there? Or you mean to add it to DataPar.json in import so that it is saved to StudyPar in derivatives?

Sorry, let me explain. So if I run the whole pipeline (DCM2BIDS, BIDS2LEGACY & all modules), I pass a single `sourceStructure.json` to `ExploreASL_Master`. The `ExploreASL_Initialize` does search for the `studyPar.json` then. Can I add a `x.Atlases` field to the `studyPar.json`, so that it is within the `DataPar.json` for the normal pipeline, later?

**Comment by MichaelStritt** [comment]
> Yes - so the question is how is this sorted in Linux and under Windows - which one flips the order and how to solve. From your comments, I am not able to guess what goes wrong - shall we have a short meeting about this?

Sorry, I don't want to annoy you with too many meetings, but it would probably be pretty helpful.

**Comment by jan-petr** [comment]
> > What exactly you mean? in normal StudyPar there is the x.S.Atlases option for this - wasn't it you adding it there? Or you mean to add it to DataPar.json in import so that it is saved to StudyPar in derivatives?
> 
> Sorry, let me explain. So if I run the whole pipeline (DCM2BIDS, BIDS2LEGACY & all modules), I pass a single `sourceStructure.json` to `ExploreASL_Master`. The `ExploreASL_Initialize` does search for the `studyPar.json` then. Can I add a `x.Atlases` field to the `studyPar.json`, so that it is within the `DataPar.json` for the normal pipeline, later?
> I could also add an option within this issue, I just wasn't sure about how we're doing this right now.

Yes. Sorry. Forgot about that. You can indeed add studyPar.json and it will be copied to derivatives...

**Comment by MichaelStritt** [comment]
Ah okay, thanks, I'll try that :)

**Comment by jan-petr** [comment]
> > Yes - so the question is how is this sorted in Linux and under Windows - which one flips the order and how to solve. From your comments, I am not able to guess what goes wrong - shall we have a short meeting about this?
> 
> Sorry, I don't want to annoy you with too many meetings, but it would probably be pretty helpful.

Haha. No worries - emails annoy me equally :) Just joking - there's always a point when a single person gets stuck and a discussion helps. And you are definitively not asking for each trivial thing :D

**Comment by MichaelStritt** [comment]
> 
> 
> > `ASL4D_a_2` definitely looks like an m0 scan to me and `ASL4D_1` should be a PWI.
> 
> Yes - so the question is how is this sorted in Linux and under Windows - which one flips the order and how to solve. From your comments, I am not able to guess what goes wrong - shall we have a short meeting about this?

Just ran it on linux. There it seems to be the same :/

**Comment by MichaelStritt** [comment]
What I don't get is, if we already know that the first half of the slices are ASL and the second half is M0, we could create two separate NIFTIs. Why do we merge them?

**Comment by jan-petr** [comment]
Some comments - I have fixed the DcmtkRead and add all new compiled version. It should work, but please check. And be careful about what it gives as data types. I have changed studyID from int to string. But you can make the conversion int he DcmtkRead matlab wrapper.

**Comment by jan-petr** [comment]
I can't test it much, because the code crashes now in the M0-PWI sorting. This is fine - just saying why I can't test it :)

Do not call xASL_io_DcmtkRead in xASL_imp_DCM2NII_Subject_ImageTypeVsInstanceNumber and do not call it anywhere else.  There is a function called xASL_bids_Dicom2JSON that already reads all the DICOMs and stores all the relevant info. It is now called somewhere inside xASL_imp_DCM2NII_Subject and it should really get all the DICOM headers - because reading DICOMs twice will take a lot of time. The thing is that inside xASL_bids_Dicom2JSON, I make a presorting of fields - check lines 85-88. Certain fields, I save only once - like the long Phoenix. Certain fields, I save for each DICOM, certain I throw away. See and edit it there - it should be easy.

BTW: We have to be a bit careful about this issue. We have restructured the whole script. And now we modify small parts of it. It is very difficult to trace changes then in the overall difference. Such a thing is then prone to errors. Unfortunately - not your fault :) We might have to then separate the reorganizational commits and editing commits and review them separately. 

And move more major changes to different issues.

**Comment by MichaelStritt** [comment]
> Do not call xASL_io_DcmtkRead in xASL_imp_DCM2NII_Subject_ImageTypeVsInstanceNumber and do not call it anywhere else. There is a function called xASL_bids_Dicom2JSON that already reads all the DICOMs and stores all the relevant info. It is now called somewhere inside xASL_imp_DCM2NII_Subject and it should really get all the DICOM headers - because reading DICOMs twice will take a lot of time. The thing is that inside xASL_bids_Dicom2JSON, I make a presorting of fields - check lines 85-88. Certain fields, I save only once - like the long Phoenix. Certain fields, I save for each DICOM, certain I throw away. See and edit it there - it should be easy.

Sure, I'll try that. The problem was that the InstanceNumber differs for each slice, so compared to the other parts where we extract the header, here we have to compare all headers, but maybe you're already doing something like this in the code. I'll try to dive in a bit deeper 👍 

> We have to be a bit careful about this issue. We have restructured the whole script. And now we modify small parts of it. It is very difficult to trace changes then in the overall difference. Such a thing is then prone to errors. 

I totally agree. The problem is that it would be hard to properly test all flavors with this GE sequence bug still in there, right?

**Comment by MichaelStritt** [comment]
Okay, so for `GE_PCASL_3Dspiral_Product_volunteer` the **ASLContext** `deltam,m0scan` should be correct. At least according to the `InstanceNumbers`:

![image](https://user-images.githubusercontent.com/46593074/115855147-3a15fa80-a42b-11eb-93e4-ff68c3fa8771.png)

Could you run the **fullBIDSPipeline** test or the normal **xASL_module_Import** for `GE_PCASL_3Dspiral_Product_volunteer`? Because it seems that it's correct on windows, right? So we would have to update the reference.

**Comment by jan-petr** [comment]
Fix difference 1 in GE_PCASL_3Dspiral_Product_volunteer:
DICOM has 0 in LabDur and PLD for the m0scan - we now allow this and check that this is the case for all vectors of PLD and LabDur. And modified the flavor reference.

**Comment by jan-petr** [comment]
An error from a previous version - saving TotalAcquiredFields (ASL specific parameter) to non-ASL JSONs. This is now avoided directly in the bidsPar-config

**Comment by jan-petr** [comment]
Reduce the number of Track_progress calls for large number of DICOMs to save on processing time.
