### ISSUE TITLE
xASL_io_Nifti2Im Error

### ISSUE THREAD

**Issue by MichaelStritt** [ExploreASL/ExploreASL#90]
Hey guys, just stumbled upon another error. 

Background info: current develop branch, Windows 10, compiled ExploreASL

Has to do with io of Niftis, so I also assigned Jan, hope that's ok.

![Annotation 2020-08-14 204659](https://user-images.githubusercontent.com/46593074/90283054-c2d9a100-de6f-11ea-8466-cae7ece5f3c3.png)

**Comment by jan-petr** [comment]
Hi Michael,

Of course no problem assigning me. Can you please print out all the 3 variable before the if, so that we have an idea what went wrong?

**Comment by MichaelStritt** [comment]
I've tried to debug it. Here is the code I added to the _xASL_io_Nifti2Im_ function:

```
% -----------------------------------------------------------------------------------------------------------------------------------------------------
% 6) Check scaling
% -----------------------------------------------------------------------------------------------------------------------------------------------------
% In the import stage, the scaling can go wrong. In this case, we throw a
% warning & try to correct this

if exist('imOut', 'var')
    try
        MaxIm = max(imOut(isfinite(imOut)));
        if MaxIm>1e9 && exist('Fpath', 'var') && exist('Ffile', 'var')
            if ~isempty(regexp(Ffile, '^.*(T1|FLAIR).*$'))
                warning('%s\n%s', 'Structural image with extremely high image intensities detected, resetting the maximum to 4096:', niftiIn);
                imOut = imOut.*4096./MaxIm;
            else
                warning('%s\n%s', 'Extremely high image intensities detected, check if all processing and quantification went correctly:', niftiIn);
                fprintf('This issue was seen before with erroneous interpretation of the Philips rescale slope\n');
                fprintf('We only correct this automatically for T1/FLAIR images to avoid quantification issues\n');
                fprintf('Hence for this image it is not automatically corrected\n');
            end
        end
    catch
        disp('Error in xASL_io_Nifti2Im:');
        disp('MaxIm:');
        disp(MaxIm);
        disp('Type:');
        disp(class(MaxIm));
        disp('imOut:');
        disp(imOut);
        disp('Type:');
        disp(class(imOut));
    end
end
```

And here is a part of the log file of the ASL module:

```
------------------------------------------------------------------------------------------
SPM deformation utility executed, using Nearest Neighbor interpolation
Transforming C:\Users\m.stritt\Desktop\xASL_io_Nifti2ImError\151001_2\ASL_1\FoV.nii to C:\Users\m.stritt\Desktop\xASL_io_Nifti2ImError\Population\FoV_151001_2_ASL_1.nii
 Combining transformations:
Segmentation transformation y_T1.nii of 151001_2

-----------------------------------------------------------------------
Running SPM job 'Deformations'
Done    'Deformations'
Done

xASL_Move: overwriting C:\Users\m.stritt\Desktop\xASL_io_Nifti2ImError\Population\FoV_151001_2_ASL_1.nii
Detecting vascular clusters with negative ASL signal:...

Detecting vascular clusters with negative ASL signal:...
Error in xASL_io_Nifti2Im:
MaxIm:
Type:
single
imOut:

(:,:,1) =

  Columns 1 through 13

   Inf   Inf   Inf   Inf   Inf   Inf   Inf   Inf   Inf   Inf   Inf   Inf   Inf
   Inf   Inf   Inf   Inf   Inf   Inf   Inf   Inf   Inf  -Inf  -Inf  -Inf  -Inf
   Inf   Inf   Inf   Inf   Inf   Inf   Inf   Inf   Inf   Inf   Inf   Inf   Inf
   Inf   Inf   Inf   Inf   Inf   Inf   Inf   Inf   Inf   Inf   Inf   Inf   Inf
   Inf   Inf   Inf   Inf   Inf   Inf   Inf   Inf   Inf   Inf   Inf   Inf   Inf
   Inf   Inf  -Inf   Inf   Inf   Inf   Inf   Inf   Inf   Inf   Inf   Inf   Inf
...
  Columns 105 through 117

   Inf  -Inf  -Inf  -Inf  -Inf  -Inf   Inf   Inf   Inf   Inf   Inf  -Inf  -Inf
   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
...
   Inf  -Inf
  -Inf   Inf

Type:
single
Warning: Empty CBF image, skipping...
> In xASL_im_MaskPeakVascularSignal (line 59)
  In xASL_wrp_CreateAnalysisMask (line 82)
  In xASL_module_ASL (line 415)
  In xASL_Iteration>runIteration (line 361)
  In xASL_Iteration (line 100)
  In ExploreASL_Master (line 132)

ERROR: Job iteration terminated!

ans =

    'Output argument "MaskIM" (and maybe others) not assigned during call to "xASL_im_MaskPeakVascularSignal".
     
     Error in xASL_wrp_CreateAnalysisMask (line 82)
     
     Error in xASL_module_ASL (line 415)
     
     Error in xASL_Iteration>runIteration (line 361)
     
     Error in xASL_Iteration (line 100)
     
     Error in ExploreASL_Master (line 132)'


CONT: but continue with next iteration!

Job-iteration 3 stopped at 17-Aug-2020 13:15:12 and took 846 seconds
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
```

**Comment by MichaelStritt** [comment]
Seems like there is a problem with imOut. Maybe the data is just corrupted, but I got this from Henk and thought it should be ok.

**Comment by HenkMutsaerts** [comment]
* In your debug code, if you add xASL_num2str() to the numerical output, we can see them as well.

* Your error here in debugging differs from the one from the black screen, was one a rerun of the other?
Now at the debugging, it correctly identifies that the CBF image is empty, whereas on the black screen it is a real programming error.
## if MaxIm>1e9 && exist('Fpath', 'var') && exist('Ffile', 'var')
* The error on the black screen says that we try to combine logicals but that one of the arguments is not logical. This is why it needs an & instead of && or | instead of ||. The single symbols are for single logicals, the double are for any matrix size numericals.
* The exist() won't be the problem here, it is likely the MaxIm>1e9. But it is weird that MaxIm is not singular or non-numerical, MaxIm>1e9 should give a logical 1 or 0.
* To check the above, do you mind rerunning this dataset from scratch (so not the repetition), and checking what the values are (with num2str)? Even if the data is corrupt, it should mention this (e.g. as it does correctly in your second "debug" run, by mentioning "CBF is empty"), but it should not throw an error that something is not logical ;)

Thanks!

**Comment by MichaelStritt** [comment]
Hey Henk, thanks for the quick answer!

- The output from the comment above is actually from a clean rerun with everything removed besides the basic structure.
- Using num2str is a good idea, I'll try it with that later. I'll also try if it happens in normal mode, too (not only in compiled mode). This way debugging would be a lot easier anyway.
- Isn't the problem with the logical comparison that there are NaN values in imOut? Using & or && etc. on NaN values has to lead to errors I think.

**Comment by HenkMutsaerts** [comment]
Ignore the first commit, I forgot to save before committing :) The last commit should fix this issue. This is part of the xASL_io_Nifti2Im that loads an image and automatically checks if it needs to be scaled. But if the image is empty for whatever pipeline reason, it cannot find a maximum and crashed :) So this can be safely skipped.

**Comment by MichaelStritt** [comment]
Hey, took a while to test everything. I tested it on the same dataset (clean rerun) in normal and compiled mode. Both yielded the same results. Definitely better than before, because the previous error is gone. Some minor problems are still there, but these could be from other bugs.
```xASL_Move: overwriting C:\Users\...\Population\FoV_151001_2_ASL_2.nii
Detecting vascular clusters with negative ASL signal:...100%
Warning: Empty CBF image, skipping...
> In xASL_im_MaskPeakVascularSignal (line 59)
  In xASL_wrp_CreateAnalysisMask (line 81)
  In xASL_module_ASL (line 415)
  In xASL_Iteration>runIteration (line 361)
  In xASL_Iteration (line 100)
  In ExploreASL_Master (line 132)
ERROR: Job iteration terminated!
ans =
    'Output argument "MaskIM" (and maybe others) not assigned during call to "xASL_im_MaskPeakVascularSignal".
     Error in xASL_wrp_CreateAnalysisMask (line 81)
     Error in xASL_module_ASL (line 415)
     Error in xASL_Iteration>runIteration (line 361)
     Error in xASL_Iteration (line 100)
     Error in ExploreASL_Master (line 132)'
CONT: but continue with next iteration!
...
Warning: No group susceptibility mask found, trying to use subject-wise
> In xASL_stat_GetROIstatistics (line 214)
  In xASL_wrp_GetROIstatistics (line 116)
  In xASL_module_Population (line 196)
  In xASL_Iteration>runIteration (line 361)
  In xASL_Iteration (line 100)
  In ExploreASL_Master (line 143)
Preparing ROI-based qCBF_StandardSpace_TotalGM_n=2_18-Aug-2020 statistics:
Expanding ROIs for PVC:100%Computing ROI data:50%
ERROR: Job iteration terminated!
ans =
    'Undefined function or variable 'VascularMask'.
     Error in xASL_stat_GetROIstatistics (line 603)
     Error in xASL_wrp_GetROIstatistics (line 116)
     Error in xASL_module_Population (line 196)
     Error in xASL_Iteration>runIteration (line 361)
     Error in xASL_Iteration (line 100)
     Error in ExploreASL_Master (line 143)'
CONT: but continue with next iteration!
```

**Comment by jan-petr** [comment]
Sorry to be mean, but it seems that there wasn't a problem with the nifti itself, but rather with the fact that the mask was empty, so skipping the reading is not solving the issue - and we have to find out why the mask and nifti was empty in the first place.

**Comment by MichaelStritt** [comment]
That's not mean ;) 
I can share the dataset with you & Henk if it helps, just to make sure I'm not doing anything wrong here. But even if I am doing something wrong, then the overall pipeline should probably handle this differently.

**Comment by HenkMutsaerts** [comment]
* 1. If a NIfTI is empty, the max() is empty and shouldn't crash -> so this improvement should still be there right
* 2. Yes, can you share this dataset with me? Ideally, just before it crashes (so all structural & ASL submodules have been run except for the masking part). Would be great if we can add this to hotfix 1.2.1

**Comment by jan-petr** [comment]
> * 1. If a NIfTI is empty, the max() is empty and shouldn't crash -> so this improvement should still be there right

Yes - still a valid improvement that we should keep!

**Comment by jan-petr** [comment]
Philips_2DEPI_FEAST_Longitudinal_FLAIR_LGA_ASL_PartlyDone_HiQ - see this dataset that is now crashing, but wasn't crashing on the last check of release 1.2.0...
